//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDoggyNeeds.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Dog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Size { get; set; }
        public string Breed { get; set; }
        public string Image { get; set; }

        public string Description { get; set; }
        public int Oid { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }


        public virtual Owner Owner { get; set; }
    }
}
